# import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[general]
live_config_reload = true

[terminal.shell]
program = "/bin/zsh"

[font]
size = 16

[font.normal]
family = "MesloLGM Nerd Font"
style = "Regular"

[window]
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[window.padding]
x = 10
y = 10

[window.dimensions]
columns = 160
lines = 60

[[hints.enabled]]
regex = "[^ ]+\\.\\w+:\\d+:\\d+"
command = { program = "code", args = ["--goto"] }
mouse = { enabled = true }

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
key = 'Space'
mods = 'Control'
chars = '\x00'
